---

- name: Ensure that the Docker apt repository is installed
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Ensure that the docker gpg key is installed
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Ensure that docker is up to date
  become: true
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Ensure that docker-compose is installed
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/1.17.0/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
