---

- name: Ensure that i3 is up to date
  become: true
  apt:
    name: i3
    state: latest
    update_cache: yes

- name: Ensure that the directory ~/.i3 exists
  file:
    path: ~/.i3
    state: directory

- name: Ensure that i3 statusbar configuration is up to date
  template:
    src: i3status.j2
    dest: ~/.i3/status_config

- name: Ensure that i3 configuration is up to date
  template:
    src: i3config.j2
    dest: ~/.i3/config
